theme = "dracula"

[editor]
shell = ["zsh", "-c"]
auto-save = true
cursorline = true
insert-final-newline = true
rulers = [120]
text-width = 120
line-number = "relative"
mouse = false
true-color = true
color-modes = true

[editor.smart-tab]
enable = false

[editor.file-picker]
hidden = true
git-ignore = true

[editor.lsp]
display-messages = true
display-inlay-hints = true

[editor.indent-guides]
render = true
character = "|"

[editor.soft-wrap]
enable = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.statusline]
left = ["mode", "spinner", "file-name", "position", "file-type"]
right = ["diagnostics", "selections"]

[keys.normal]
esc = ["collapse_selection", "keep_primary_selection"]

[keys.insert]
esc = ["collapse_selection", "keep_primary_selection", "normal_mode"] # deselect all; keep primary cursor only
