# # Load Antigen
source ~/.dotfiles/zsh/antigen.zsh

# # Load Antigen configurations
antigen init ~/.antigenrc

source ~/.dotfiles/zsh/aliases.zsh
# source ~/.dotfiles/zsh/functions.zsh
source ~/.dotfiles/zsh/prima.zsh

# Brew
eval "$(/opt/homebrew/bin/brew shellenv)"

# K8s
export PATH="${KREW_ROOT:-$HOME/.krew}/bin:$PATH"

# Java
export PATH="/opt/homebrew/opt/openjdk/bin:$PATH"

# Elixir
export KERL_CONFIGURE_OPTIONS="--disable-jit --with-ssl=$(brew --prefix openssl@1.1) --with-odbc=$(brew --prefix unixodbc) --enable-wx --with-wx-config=$(which wx-config)"

#Rust
export PATH="$PATH:/Users/emiliofrancischetti/.cargo/bin"

# Rancher
export PATH="/Users/emiliofrancischetti/.rd/bin:$PATH"

# Bin
export PATH="/Users/emiliofrancischetti/bin:$PATH"
export PATH="/Users/emiliofrancischetti/.local/bin:$PATH"

# ADSF
. /opt/homebrew/opt/asdf/libexec/asdf.sh

# VAUT
export VAULT_ADDR=https://vault.helloprima.com:8200

